from setuptools import setup, find_packages

setup(
    name="hummingbird",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy==1.26.4",
        "pandas==2.2.0",
        "ccxt==4.2.14",
        "ta==0.11.0",
        "pandas-ta==0.3.14b",
        "psycopg2-binary==2.9.9",
        "SQLAlchemy==2.0.27",
        "alembic==1.13.1",
        "transformers>=4.36.0",
        "torch>=2.0.0",
        "sentencepiece>=0.1.99",
        "accelerate>=0.25.0",
        "scikit-learn>=1.3.0",
        "ctransformers>=0.2.27",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "rich>=13.7.0",
        "google-generativeai==0.3.2",
        "python-dotenv==1.0.1",
        "pyyaml==6.0.1"
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="A sophisticated trading system with SMC pattern detection",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/hummingbird",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
) 