trading:
  modes:
    scalping:
      timeframes:
        - 1m
        - 5m
        - 15m
        - 1h
        - 4h
      default_timeframe: 5m
      smc_analysis:
        primary_timeframe: 5m
        secondary_timeframes: [1m, 15m, 1h, 4h]
        lookback_periods:
          1m: 100   # 100 minutes
          5m: 50    # 50 5-minute candles
          15m: 30   # 30 15-minute candles
          1h: 24    # 24 hours
          4h: 12    # 12 4-hour candles
    swing:
      timeframes:
        - 1h
        - 4h
        - 1d
      default_timeframe: 1h
      smc_analysis:
        primary_timeframe: 1h
        secondary_timeframes: [4h, 1d]
        lookback_periods:
          1h: 100
          4h: 50
          1d: 30
  position_sizing:
    risk_per_trade: 0.02  # 2% risk per trade
    max_positions: 3
    leverage: 1
  symbols:
    - BTC/USDT
    - ETH/USDT
    - SOL/USDT
  technical_indicators:
    swing:
      - RSI
      - MACD
      - SMA_20
      - SMA_50
    scalping:
      - RSI
      - MACD
      - SMA_20
      - EMA_9
  smc_strategy:
    order_blocks: true
    supply_zones: true
    demand_zones: true
    fair_value_gaps: true
    liquidity_levels: true

llm:
  default_model: "local"
  api_key: ${GEMINI_API_KEY}
  temperature: 0.8
  max_tokens: 1000
  confidence_threshold: 0.0
  top_p: 0.9
  frequency_penalty: 0.5
  presence_penalty: 0.5
  models:
    local:
      type: "local"
      name: "mistral-7b-instruct-v0.1"
      model_path: "models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
      context_length: 2048
      max_tokens: 1000
      temperature: 0.8
      top_p: 0.9
      system_prompt: "You are an expert cryptocurrency scalping analyst specializing in Smart Money Concepts (SMC) and technical analysis. Your goal is to identify high-probability trading opportunities in short-term price movements. Generate trading signals when you see clear entry points with good risk-reward ratios. Be proactive in identifying opportunities, but maintain strict risk management. Focus on recent price action, volume, and SMC patterns."
    gemini:
      type: "api"
      name: "gemini-2.0-flash"
      api_key: ${GEMINI_API_KEY}
      max_tokens: 1000
      temperature: 0.8
      system_prompt: "You are an expert cryptocurrency scalping analyst specializing in Smart Money Concepts (SMC) and technical analysis. Your goal is to identify high-probability trading opportunities in short-term price movements by analyzing multiple timeframes (1m, 5m, 15m, 1h, 4h).

When analyzing market conditions, follow this structured approach:

1. Multi-timeframe Analysis:
   - Start with higher timeframes (4h, 1h) to identify overall trend and major SMC levels
   - Use medium timeframes (15m, 5m) for entry timing and intermediate SMC patterns
   - Use lower timeframes (1m) for precise entry points and short-term SMC patterns

2. SMC Pattern Analysis:
   - Order Blocks: Look for institutional order blocks across timeframes
   - Fair Value Gaps (FVG): Identify gaps that need to be filled
   - Liquidity Levels: Find key support/resistance levels with high volume
   - Smart Money Traps: Detect potential liquidity sweeps

3. Signal Generation Rules:
   - Strong signals (confidence > 0.7):
     * Multiple timeframe alignment
     * Clear SMC patterns on 2+ timeframes
     * Strong volume confirmation
     * Good risk-reward ratio (1:2 or better)
   
   - Moderate signals (confidence > 0.5):
     * Two timeframe alignment
     * Clear SMC pattern on primary timeframe
     * Decent volume confirmation
     * Risk-reward ratio at least 1:1.5
   
   - Weak signals (confidence > 0.3):
     * Single timeframe alignment
     * Potential SMC pattern forming
     * Basic volume confirmation
     * Risk-reward ratio at least 1:1

4. Entry Conditions:
   - Price near key SMC level (within 0.5% for scalping)
   - Technical indicators aligned (RSI, MACD, EMAs)
   - Volume confirmation on entry timeframe
   - Clear market structure (trend, support/resistance)
   - No conflicting signals on higher timeframes

5. Exit Conditions:
   - Price reaches key SMC level
   - Structure shift on primary timeframe
   - Technical indicator divergence
   - Volume decline
   - Risk-reward target reached

6. Risk Management:
   - Stop loss: Place below/above nearest SMC level
   - Take profit: Use SMC levels for targets
   - Position size: Based on risk percentage
   - Maximum loss per trade: 1% of account

Generate BUY/SELL signals when you see at least 2-3 confirming factors from the above criteria. Use HOLD when:
- No clear directional bias across timeframes
- Conflicting signals between timeframes
- Price in a tight range with no clear breakout
- Risk-reward ratio below 1:1.5
- No strong SMC levels nearby

Always provide detailed reasoning for your signal generation, including:
1. Overall market structure
2. Key SMC patterns identified
3. Technical indicator alignment
4. Volume analysis
5. Risk-reward assessment"

data:
  source: "binance"
  historical_data_days: 7  # Reduced for scalping to focus on recent data
  update_interval: 10  # Changed from 20 to 60 seconds
  rate_limit: true
  min_data_points: 1000
  binance:
    testnet: false
    api_key: ${BINANCE_API_KEY}
    api_secret: ${BINANCE_API_SECRET}

risk_management:
  swing:
    max_position_size: 0.1  # 10% of portfolio
    max_daily_trades: 5
    stop_loss_percentage: 0.02  # 2%
    take_profit_levels:
      - 0.03  # 3%
      - 0.05  # 5%
      - 0.08  # 8%
  scalping:
    max_position_size: 0.05  # 5% of portfolio
    max_daily_trades: 10
    stop_loss_percentage: 0.01  # 1%
    take_profit_levels:
      - 0.02  # 2%
      - 0.03  # 3%

visualization:
  show_progress: true
  show_market_status: true
  show_technical_indicators: true
  show_patterns: true
  show_signals: true

monitoring:
  interval: 10  # Changed from 60 to 10 seconds between analyses
  error_delay: 60  # 1 minute delay on error
  max_retries: 3  # Maximum number of retries on error
  timeout: 30  # Timeout for API calls in seconds
  alerts:
    pnl_threshold: 0.02  # 2% PnL threshold for alerts
    structure_shift: true
    reversal_pattern: true
    liquidity_level: true
  position_management:
    trailing_stop: true
    trailing_stop_distance: 0.02  # 2% distance
    dynamic_take_profit: true
    max_loss: 0.05  # 5% maximum loss
    profit_target: 0.1  # 10% profit target

technical:
  indicators:
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    ema:
      short_period: 8
      long_period: 21
  smc:
    order_block:
      min_strength: 0.2
      max_lookback: 20
    fair_value_gap:
      min_size: 0.00002
      max_lookback: 15
    liquidity_level:
      min_volume: 50
      min_touches: 1
      max_deviation: 0.0001

database:
  url: postgresql://postgres:postgres@localhost:5432/hummingbird
  host: localhost
  port: 5432
  name: hummingbird
  user: postgres
  password: postgres

position:
  min_strength: 0.6  # minimum position strength to maintain
  max_positions: 5  # maximum number of concurrent positions
  risk_per_trade: 0.02  # 2% risk per trade
  max_daily_loss: 0.05  # 5% maximum daily loss

market_structure:
  order_block:
    min_volume_multiplier: 1.2
    min_body_size: 0.0005
    max_lookback: 20
  
  fair_value_gap:
    min_gap_size: 0.0002
    max_fill_time: 48
  
  liquidity_level:
    min_touches: 2
    max_deviation: 0.0005
    volume_threshold: 1.1 